#' Extract unique RepeatMasker sequences to a fasta file
#'
#' This function will extract all unique RepeatMasker sequences from the genome
#' using the BED file generated by rmskToBed() and export these sequences to a
#' new fasta file in the rmskProfiler cache for downstream index generation. In
#' addition to producing a fasta file of the unique sequences, a json file named
#' rmsk-duplicateInfo.json is also saved to the cache which maps SHA1 hash values
#' of sequences to records in the BED file.
#'
#' @param species Either "Hs" (Homo sapiens) or "Mm" (Mus musculus)
#' @param exclude A character vector specifying which elements (repClass) were
#' excluded by \code{rmskToBed()}. Default "Simple_repeat", "Low_complexity",
#' "Satellite", "RNA", "rRNA", "snRNA", "scRNA", "srpRNA", "tRNA", and "Unknown".
#' @param min_len Minimum sequence length of a record used by \code{rmskToBed()}.
#' Default 32.
#' @param cache NULL, a path to a cache directory, or a BiocFileCache object.
#' Default NULL uses the rmskProfiler cache at
#' \code{tools::R_user_dir("rmskProfiler", which = "cache")}.
#'
#' @return NULL
#' @export
#'
#' @examples
#' \dontrun{
#' extractUniqueSeqs(species = "Hs")
#' }
extractUniqueSeqs <- function(
  species = c("Hs", "Mm"),
  exclude = .DEFAULT_EXCLUDE,
  min_len = 32,
  cache = NULL
) {
  species <- match.arg(species)
  reticulate::py_require("pybedtools")
  reticulate::py_require(python_version = ">=3.10")
  reticulate::source_python(system.file(
    "python",
    "rmsk_profiler.py",
    package = "rmskProfiler",
    mustWork = TRUE
  ))

  bfc <- .getCache(cache)
  key <- .settingsKey(exclude, min_len)
  genome_fa <- .getResource(
    bfc,
    .gencodeRname(species, "genome"),
    hint = "Run downloadResources() first."
  )
  rmsk_bed <- .getResource(
    bfc,
    .rname(species, "rmsk.bed", key),
    hint = "Run rmskToBed() with the same species, exclude, and min_len first."
  )
  out_json <- .newResource(
    bfc,
    .rname(species, "rmsk-duplicateInfo.json", key),
    ext = ".json"
  )
  out_fa <- .newResource(
    bfc,
    .rname(species, "rmsk-unique.fa.gz", key),
    ext = ".fa.gz"
  )

  # Genome fasta needs to be unzipped to work with pybedtools. Unzip into the
  # cache directory since it is large, and remove it and its index when done
  uz_genome_fa <- tempfile(
    "genome",
    tmpdir = BiocFileCache::bfccache(bfc),
    fileext = ".fa"
  )
  uz_rmsk_fa <- tempfile(
    "rmsk-unique",
    tmpdir = BiocFileCache::bfccache(bfc),
    fileext = ".fa"
  )
  on.exit(
    unlink(c(uz_genome_fa, paste0(uz_genome_fa, ".fai"), uz_rmsk_fa)),
    add = TRUE
  )
  message("Unzipping ", basename(genome_fa))
  R.utils::gunzip(genome_fa, destname = uz_genome_fa, remove = FALSE)

  tryCatch(
    extract_unique_records(rmsk_bed, uz_genome_fa, out_json, uz_rmsk_fa),
    warning = function(w) print(w),
    error = function(e) {
      stop("An error occured during fasta extraction!")
    }
  )
  message("Gzipping unique RepeatMasker sequences...")
  R.utils::gzip(
    uz_rmsk_fa,
    destname = out_fa,
    remove = TRUE,
    overwrite = TRUE
  )

  return(invisible(NULL))
}
