#' Extract unique RepeatMasker sequences to a fasta file
#'
#' This function will extract all unique RepeatMasker sequences from the genome
#' using the BED file generated by rmskToBed() and export these sequences to a
#' new fasta file for downstream index generation. In addition to producing a
#' fasta file of the unique sequences, a json file is also dumped to the
#' resource directory named rmsk-duplicateInfo.json which maps SHA1 hash values
#' of sequences to records in the BED file.
#'
#' @param resource_dir Path to the directory containing index generation resources.
#' Output is saved to this location.
#'
#' @return NULL
#' @export
#'
#' @examples
#' \dontrun{
#' extractUniqueSeqs(resource_dir = "/path/to/rmsk-resources")
#' }
extractUniqueSeqs <- function(resource_dir) {

  resources <- list.files(resource_dir, full.names = TRUE)
  genome_fa <- grep("primary_assembly.genome.fa.gz", resources, value = TRUE)
  rmsk_bed <- grep("fa.out.bed", resources, value = TRUE)

  if (length(genome_fa) != 1) {
    stop("<>.primary_assembly.genome.fa.gz file not found in given directory. Check that the file exists")
  }
  if(length(rmsk_bed) != 1) {
    stop("<>.fa.out.bed file not found in given directory. Check that the file exists")
  }

  # Genome fasta needs to be unzipped to work with pybedtools
  uz_genome_fa <- gsub(".gz", "", genome_fa)
  if (file.exists(uz_genome_fa)) {
    message(basename(uz_genome_fa), " has already been unzipped. Skipping")
  } else {
    message("Unzipping ", basename(genome_fa))
    R.utils::gunzip(genome_fa, remove = FALSE)
  }

  tryCatch(
    rmsk_profiler$extract_unique_records(rmsk_bed, uz_genome_fa),
    warning = function(w) print(w),
    error = function(e) {
      stop("An error occured during fasta extraction!")
    }
  )
  message("Gzipping unique RepeatMasker sequences...")
  R.utils::gzip(file.path(resource_dir, "rmsk-unique.fa"), remove = TRUE, overwrite = TRUE)

  # Unzipped version of the genome_fa can be safely removed
  file.remove(uz_genome_fa)

  return(invisible(NULL))
}
